### ISSUE TITLE
App Measurement 2.25.0

### ISSUE THREAD

**Issue by Morish24** [adobe/appmeasurement#1]
App Measurement is erroring out as the try catch block is missing, which is causing the script to fail entierly, our previous code includes the try catch block at the same location, but the latest version is missing.

try{ var q = h.AppMeasurement.uc; } catch(e){}

![image](https://github.com/adobe/appmeasurement/assets/101344984/c0876f28-d48d-4b85-8b41-90fc704b992a)

**Comment by liljenback** [comment]
Thanks @Morish24 for the report. Could you provide steps to reproduce the problem you're guarding for?

**Comment by Morish24** [comment]
Hi, When the AppMeasurement is being loaded for the first time, on our webpages we are seeing that h.AppMeasurement often comes as undefined as we dont use the default s global object, we use a different global object lets call it s_test where the AppMeasurement is available.

So it always breaks for us here.

![image](https://github.com/adobe/appmeasurement/assets/101344984/74676c02-a831-4fba-8466-2e987702df2b)

**Comment by liljenback** [comment]
Do you use `s_gi` to get your instance?

**Comment by Morish24** [comment]
Yes

**Comment by liljenback** [comment]
Thanks, can you provide a code snippet that reproduces this issue?

**Comment by liljenback** [comment]
This has been resolved in [AppMeasurement 2.27.0](https://github.com/adobe/appmeasurement/releases/tag/v2.27.0).
