### ISSUE TITLE
Time always set to Month - 1

### ISSUE THREAD

**Issue by Morish24** [adobe/appmeasurement#3]
Hi, not sure if this is an expected behaviour or not, but have noticed that the t variable set in b/ss calls always set month = month -1

Mon Apr 08 2024 22:55:34 GMT+0530 (India Standard Time) this is the b variable.

when we run b.getMonth() it will return 3, as getMonth  are zero-indexed.

![image](https://github.com/adobe/appmeasurement/assets/101344984/b4aafd86-f294-4429-bf66-c492c47abac8)

![image](https://github.com/adobe/appmeasurement/assets/101344984/6c0c2a41-8ac6-4f17-b068-e17284481f79)

Can you fix this ?

**Comment by liljenback** [comment]
The `t` query parameter is comprised by values obtained by the JavaScript [Date][1] object as specified in the [query parameter documentation][2]. There are currently no plans on changing the format to something else.

[1]: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/getMonth
[2]: https://experienceleague.adobe.com/en/docs/analytics/implementation/validate/query-parameters
