### ISSUE TITLE
bufferRequests is not buffering request most of the times.

### ISSUE THREAD

**Issue by Morish24** [adobe/appmeasurement#4]
we are trying to implement buffer requests to prevent out calls getting cancelled on page unload or specific events.

https://experienceleague.adobe.com/en/docs/analytics/implementation/vars/functions/bufferrequests

We are setting s.bufferRequests(true) before our linktrack call fires from the code, most of the time, when this is done programetically, we do not see the request getting buffered, but when we so the same by adding it to console, the buffer request works, is there a flag or something we can log to see if the flag is set or not, just to debug the possiblity of this working on some cases ?

` if (bufferRequests) {
        s_dell.bufferRequests(true);
        setTimeout(function () {
            s_dell.bufferRequests(false);
        }, 5000);
    }`
    
    This is how we are using, and most of the times calls are getting triggered immediatly instead of getting buffered.
    
    Please help !

**Comment by liljenback** [comment]
If session storage is available then buffered requests are stored in under key `AppMeasurement.requests` with an `account` suffix details. Please share if you have an example where this can consistently be reproduced.

**Comment by Morish24** [comment]
Hi @liljenback , we are able to consistently reproduce this, i can show you the example, is there a way to connect ?

**Comment by liljenback** [comment]
It is recommended to keep the buffer requests feature turned on until the page unloads. In this case the timer might complete too early resulting in another request attempt which gets cancelled.
